### ISSUE TITLE
Replace with $worker->setLogger($logger);

### ISSUE THREAD

**Issue by dabreu2** [resque/php-resque#57] opened 2022-01-24 12:55 UTC
https://github.com/resque/php-resque/blob/daa339905288e6c9f5244e12dd853a9c53cf2299/bin/resque#L116
https://github.com/resque/php-resque/blob/daa339905288e6c9f5244e12dd853a9c53cf2299/bin/resque#L173

**Comment by dabreu2** [comment] 2022-01-24 12:56
This not work use $worker->setLogger($logger); instead

**Comment by Benoit-amo** [comment] 2022-01-24 13:07
👍🏼

**Comment by danhunsaker** [comment] 2022-01-27 16:59
Duplicate of #39 

This was a case of a change in the way Resque works not being propagated to the bin. Instead of configuring the logger level on the worker, we now directly set the logger instance, which lets Resque support any PSR-compliant logger, such as the one used by $framework.

This has been fixed, now, so I'm closing the issue. Sorry for the long delay on getting to it, and thanks to @dabreu2 for the PR.

**Closed by danhunsaker** 2022-01-27 16:59 UTC
